project:
  type: website

website:
  title: "JGI Citation Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format: 
  html:
    code-fold: true
    theme:
          light: flatly
          dark: darkly
    toc: true