---
title: "About"
---

Notebooks and other artifacts depicting our work on JGI's citation context analsis problem


# [How we plan to go about tackling this problem:]{style="background-color:white; color:green"}


1. Identify [which]{style="color:green; background-color:yellow"} publications likely are leveraging genomic data
    i) Given a set of identifiers, can we identify which publications are incorporating those datasets?
2. Figure out [where]{style="color:green;background-color:yellow"} folks are describing usage in publications
    i) Can we take the entire content of an article, identify all descriptions of data usage, and link usage descriptions to datasets being cited?
3. Figure out [how]{style="color:green;background-color:yellow"} something is being used
    i) Once we've determined that a citation of a dataset is valid and identified areas of an article describing usage, can we determine how something is being used in its local context within the document?
        A) i.e. 'built a phylogenetic tree'
    ii) Given #1, #3 has to have an answer. #2 is a necessary step for determining #3 once #1 is established
4. Figure out [why]{style="color:green;background-color:yellow"} something is being used
    i) Can we determine how the specific data use case relates to (a) the purpose of the study and (b) the conclusions/results of the study? 